### PR TITLE
Collection of 8 regular frames

### PR DESCRIPTION
**Pull request by NeoRame**
Start to create Frames for the frames selection.
If anyone has a nice idea or a special wish, feel free to contact me ;) i'm open for ideas

### CODE REVIEW

**Comment by untoxa** [comment]
oh, very nice indeed. we need 8 regular and 8 big frames, let's make the regular frames set first and put it into the program.

**Comment by NeoRame** [comment]
I know ;) that's why I said "start to create"
Plan was first the 8 simple and than 8 wild. For this I collecting ideas :D

But as I said, I need some days... work in real life, brainstorming for ideas and the weather in Germany XD

**Comment by untoxa** [comment]
i was just describing the scope of the task. currently we have no rules for the pull requests, but it may be very nice if they are self-contained and have the description for the target parameters, so i can look inside and see, if it is ready for merge or not yet.

**Comment by NeoRame** [comment]
simple eight are done i think ;)

**Pull request merged**
